.PHONY: clean All

All:
	@echo "----------Building project:[ laba1_chast2 - Debug ]----------"
	@"$(MAKE)" -f  "laba1_chast2.mk"
clean:
	@echo "----------Cleaning project:[ laba1_chast2 - Debug ]----------"
	@"$(MAKE)" -f  "laba1_chast2.mk" clean
